### ISSUE TITLE
TensorboardCallback throws `KeyError: 'st_tuner_time'`

### ISSUE THREAD

**Issue by ConnorBaker** [awslabs/syne-tune#411]
## Overview

> A reproducible test case or series of steps

See below.

> The version of our code being used

This occurs both on the latest release, v0.3.2, and against master (I tested against c5229561068d37d621d70719e4ded6c05b0f463b).

> Any modifications you've made relevant to the bug

Swapping the order of these two lines seems to resolve this: https://github.com/awslabs/syne-tune/blob/main/syne_tune/tuner_callback.py#L197-L198. The driver is the MOASHA example from this repo, adjusted for MNIST: https://github.com/awslabs/syne-tune/blob/main/examples/launch_height_moasha.py.

While this is a model wrapped with PyTorch Lightning, I suspect it will occur with a regular PyTorch model, but haven't had the chance to reproduce.

> Anything unusual about your environment or deployment

I'm using an M1 MacBook Pro with Python 3.8.13, PyTorch 1.13.0, and PyTorch Lightning 1.7.7. 

## Problem Description

Hello all,

I'm trying to run a simple tuning example using a PyTorch-Lightning wrapped model on the MNIST dataset. I've attached the relevant files for you to try to reproduce.

The error I'm seeing is reproduced below; it's `TensorboardCallback` throwing `KeyError: 'st_tuner_time'`. I think it was introduced here https://github.com/awslabs/syne-tune/pull/287/files#diff-341cb85f30208b5068c48fe1e8ef02b87978451adb09671b5ced7d810c6413aaR199 by not allowing the object to set its time fields. Swapping the order of those two lines seems to fix it.

Any ideas?

Warm regards,
Connor Baker

## Error

```bash
$ python moasha.py
INFO:syne_tune.tuner:results of trials will be saved on /Users/connorbaker/syne-tune/mnist-2022-11-01-21-46-04-934
INFO:syne_tune.tuner_callback:Logging tensorboard information at /Users/connorbaker/syne-tune/mnist-2022-11-01-21-46-04-934/tensorboard_output, to visualize results, run
tensorboard --logdir /Users/connorbaker/syne-tune/mnist-2022-11-01-21-46-04-934/tensorboard_output
INFO:root:Error launching /usr/bin/nvidia-smi, no GPU could be detected.
INFO:root:Detected 0 GPUs
INFO:root:running subprocess with command: /Users/connorbaker/micromamba/envs/bsrt-mac/bin/python mnist.py --layer_1_size 180 --layer_2_size 55 --lr 0.7151922144787557 --st_checkpoint_dir /Users/connorbaker/syne-tune/mnist-2022-11-01-21-46-04-934/0/checkpoints
adding trial 0
INFO:syne_tune.tuner:(trial 0) - scheduled config {'layer_1_size': 180, 'layer_2_size': 55, 'lr': 0.7151922144787557}
ERROR:syne_tune.tuner:An error happened during the tuning, cleaning up resources and logging final resources before throwing the exception.
INFO:syne_tune.tuner_callback:Tensorboard information has been logged at /Users/connorbaker/syne-tune/mnist-2022-11-01-21-46-04-934/tensorboard_output, to visualize results, run
tensorboard --logdir /Users/connorbaker/syne-tune/mnist-2022-11-01-21-46-04-934/tensorboard_output
INFO:syne_tune.tuner:Stopping trials that may still be running.
INFO:syne_tune.tuner:Tuning finished, results of trials can be found on /Users/connorbaker/syne-tune/mnist-2022-11-01-21-46-04-934
Traceback (most recent call last):
  File "moasha.py", line 60, in <module>
    tuner.run()
  File "/Users/connorbaker/micromamba/envs/bsrt-mac/lib/python3.8/site-packages/syne_tune/tuner.py", line 250, in run
    raise e
  File "/Users/connorbaker/micromamba/envs/bsrt-mac/lib/python3.8/site-packages/syne_tune/tuner.py", line 185, in run
    new_done_trial_statuses, new_results = self._process_new_results(
  File "/Users/connorbaker/micromamba/envs/bsrt-mac/lib/python3.8/site-packages/syne_tune/tuner.py", line 356, in _process_new_results
    done_trials_statuses = self._update_running_trials(
  File "/Users/connorbaker/micromamba/envs/bsrt-mac/lib/python3.8/site-packages/syne_tune/tuner.py", line 476, in _update_running_trials
    callback.on_trial_result(
  File "/Users/connorbaker/micromamba/envs/bsrt-mac/lib/python3.8/site-packages/syne_tune/tuner_callback.py", line 197, in on_trial_result
    walltime = result[ST_TUNER_TIME]
KeyError: 'st_tuner_time'
```

## `moasha.py`

```python
# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.
"""
Example showing how to tune multiple objectives at once of an artificial function.
"""
import logging
from pathlib import Path

import numpy as np
from syne_tune import StoppingCriterion, Tuner
from syne_tune.backend import LocalBackend
from syne_tune.config_space import randint, uniform
from syne_tune.optimizer.schedulers.multiobjective import MOASHA
from syne_tune.tuner_callback import TensorboardCallback

if __name__ == "__main__":
    logging.getLogger().setLevel(logging.INFO)
    np.random.seed(0)

    config_space = {
        "layer_1_size": randint(8, 256),
        "layer_2_size": randint(8, 256),
        "lr": uniform(1e-5, 1.0),
    }
    entry_point = Path(__file__).parent / "mnist.py"
    np.random.seed(0)
    scheduler = MOASHA(
        max_t=10,
        grace_period=3,
        time_attr="epoch",
        mode=["min", "max"],
        metrics=["val_loss", "val_accuracy"],
        config_space=config_space,
    )
    trial_backend = LocalBackend(entry_point=entry_point.as_posix())

    stop_criterion = StoppingCriterion(max_wallclock_time=600)
    tuner = Tuner(
        trial_backend=trial_backend,
        scheduler=scheduler,
        stop_criterion=stop_criterion,
        n_workers=1,
        sleep_time=0.5,
        print_update_interval=5.0,
        callbacks=[TensorboardCallback()],
    )
    tuner.run()
```

## `mnist.py`

```
import logging
import os
from argparse import ArgumentParser

import pytorch_lightning as pl
import torch
from filelock import FileLock
from syne_tune import Reporter
from torch.nn import functional as F
from torch.utils.data import DataLoader, random_split
from torchvision import transforms
from torchvision.datasets import MNIST


class LightningMNISTClassifier(pl.LightningModule):
    """
    This has been adapted from
    https://towardsdatascience.com/from-pytorch-to-pytorch-lightning-a-gentle-introduction-b371b7caaf09
    """

    def __init__(self, config, data_dir=None):
        super(LightningMNISTClassifier, self).__init__()

        self.data_dir = data_dir or os.getcwd()

        self.layer_1_size = config["layer_1_size"]
        self.layer_2_size = config["layer_2_size"]
        self.lr = config["lr"]
        self.batch_size = config["batch_size"]
        self.reporter: Reporter = config["reporter"]

        # mnist images are (1, 28, 28) (channels, width, height)
        self.layer_1 = torch.nn.Linear(28 * 28, self.layer_1_size)
        self.layer_2 = torch.nn.Linear(self.layer_1_size, self.layer_2_size)
        self.layer_3 = torch.nn.Linear(self.layer_2_size, 10)

    def forward(self, x):
        batch_size, channels, width, height = x.size()
        x = x.view(batch_size, -1)

        x = self.layer_1(x)
        x = torch.relu(x)

        x = self.layer_2(x)
        x = torch.relu(x)

        x = self.layer_3(x)
        x = torch.log_softmax(x, dim=1)

        return x

    def cross_entropy_loss(self, logits, labels):
        return F.nll_loss(logits, labels)

    def accuracy(self, logits, labels):
        _, predicted = torch.max(logits.data, 1)
        correct = (predicted == labels).sum().item()
        accuracy = correct / len(labels)
        return torch.tensor(accuracy)

    def training_step(self, train_batch, batch_idx):
        x, y = train_batch
        logits = self.forward(x)
        loss = self.cross_entropy_loss(logits, y)
        accuracy = self.accuracy(logits, y)

        self.log("ptl/train_loss", loss)
        self.log("ptl/train_accuracy", accuracy)
        return loss

    def validation_step(self, val_batch, batch_idx):
        x, y = val_batch
        logits = self.forward(x)
        loss = self.cross_entropy_loss(logits, y)
        accuracy = self.accuracy(logits, y)
        return {"val_loss": loss, "val_accuracy": accuracy}

    def validation_epoch_end(self, outputs):
        avg_loss = torch.stack([x["val_loss"] for x in outputs]).mean()
        avg_acc = torch.stack([x["val_accuracy"] for x in outputs]).mean()
        self.log("ptl/val_loss", avg_loss)
        self.log("ptl/val_accuracy", avg_acc)
        self.reporter(
            epoch=self.current_epoch,
            val_loss=avg_loss.item(),
            val_accuracy=avg_acc.item(),
        )

    @staticmethod
    def download_data(data_dir):
        transform = transforms.Compose(
            [transforms.ToTensor(), transforms.Normalize((0.1307,), (0.3081,))]
        )
        with FileLock(os.path.expanduser("~/.data.lock")):
            return MNIST(data_dir, train=True, download=True, transform=transform)

    def prepare_data(self):
        mnist_train = self.download_data(self.data_dir)

        self.mnist_train, self.mnist_val = random_split(mnist_train, [55000, 5000])

    def train_dataloader(self):
        return DataLoader(self.mnist_train, batch_size=int(self.batch_size))

    def val_dataloader(self):
        return DataLoader(self.mnist_val, batch_size=int(self.batch_size))

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.lr)
        return optimizer


if __name__ == "__main__":
    root = logging.getLogger()
    root.setLevel(logging.INFO)

    parser = ArgumentParser()
    parser.add_argument("--layer_1_size", type=int)
    parser.add_argument("--layer_2_size", type=int)
    parser.add_argument("--lr", type=float)

    args, _ = parser.parse_known_args()
    config = {
        "layer_1_size": args.layer_1_size,
        "layer_2_size": args.layer_2_size,
        "lr": args.lr,
        "reporter": Reporter(),
        "batch_size": 128,
    }

    model = LightningMNISTClassifier(config)
    trainer = pl.Trainer(
        max_epochs=10,
        enable_progress_bar=False,
        accelerator="cpu",
        devices="1",
        num_sanity_val_steps=0,
    )
    trainer.fit(model)
```

**Comment by aaronkl** [comment]
Thanks for the catch. This is also mention in #410 . Should be fixed in #412
